### ISSUE TITLE
Feature Request: Attenuverters on CMP's outputs

### ISSUE THREAD

**Issue by VegaDeftwing** [bogaudio/BogaudioModules#123]
![image](https://user-images.githubusercontent.com/11283620/86653886-276d2a80-bfab-11ea-9b0e-8b87421d9286.png)

I almost always use CMP as a distortion effect emulating the 'box' output on the Mystic Circuit's Ana hardware module. Having attenuverters on the two comparison outputs would really help clean up the clutter. This could also just be a separate module, as the lag control is useless when used like this too, and a dedicated mix out instead of the not would make it fit well. Thanks!

**Comment by mdemanett** [comment]
I think I get what you're doing -- but if you have a test patch .vcv file handy, that'd be a help.  Will look into it.

**Comment by VegaDeftwing** [comment]
https://drive.google.com/file/d/1SDPQ8UUFGod2QtMaqc00U-WCpsUDU54s/view?usp=sharing
(Requires Bogaudio, VCV fundamental, and Audible Instruments)

There's a lot of notes in the patch, hope this helps!

**Comment by mdemanett** [comment]
I got around to this -- thanks for the detailed patch, was very helpful.

It doesn't perfectly replicate your patch, but certainly throws out some gnarly tones.  On the releases page here, the latest test release (-test8) has installable builds that include this, if you want to test it.  Otherwise I expect to release this stuff to Rack this week.

![Screen Shot 2020-07-19 at 9 35 55 PM](https://user-images.githubusercontent.com/49971/87891528-4c7c8700-ca08-11ea-969f-24124a8f4ab5.png)

**Comment by VegaDeftwing** [comment]
Not *exactly* the same but still super cool and the dry/wet was definitely a good call. This is amazing!

I know I'm a random internet stranger but thank you, you really made my day. I just got a 7 string guitar this week (by selling 3 other guitars, an amp, and more) but I've been to under the weather to feel motivated to even play it. I may still feel like butt, but this got me to plug it in and have some fun, and got a smile out of me. I'll try a lot of patching with it and let you know if I find any bugs.

**Comment by VegaDeftwing** [comment]
the WNDW cv input is showing up as an output instead of an input, and not outputting anything. Also, sort of expected but maybe not desirable- the mix output is hot when nothing is connected. So far everything else is working well and sounds excellent.

**Comment by mdemanett** [comment]
Thanks for the testing!  I pushed a fix for the WINDOW input (somehow wires were crossed and a stray output that shouldn't have been there was being created and displayed over the top of the window input).  The output with no input thing is also a good catch; I fixed things so the output is zero when the knobs are at default positions, but it'll still be possible to get non-zero DC out with other knob positions, since at heart it's a comparator.  Better than getting a weird wave as before.
