### ISSUE TITLE
Question: Sine VCO Linear vs Exponential mode

### ISSUE THREAD

**Issue by Deevje** [bogaudio/BogaudioModules#124]
Hey Matt,

I was using your Sine VCO in linear frequency mode so I could change the frequency in predefined increments for Ring Mod and FM purposes, and I noticed that, as soon as I connect something to the FM input on Exponential (for melody purposes) and open the attenuverter, it no longer holds its predefined frequency, even if there is 0V coming in.

Similarly, when I use the V/Oct for melody purposes and try to use the FM input on linear mode for the ratio, it seems as if the FM input behaves the same as the Phase input, only reacting to changing values, it doesn't react to steady voltage.

Is there a way I can control the oscillator exponentially at the same time as linearly?

Kind regards,
Deev

**Comment by mdemanett** [comment]
Looks like a bug with the 0V FM input and linear mode -- will look into it.  

A DC or slow-moving input with linear FM works as you say -- it's just a phase offset.  The linear FM is implemented as phase modulation, which at audio rate does the right thing.  

When the bug is fixed, hopefully your first approach does what you want.  Another way, or as a workaround maybe, might be to mix the control signals externally, and send that mix to the V/O input.
