### ISSUE TITLE
MUMIX - missed Average option in right-click menu

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#135]
Hi Matt! There is an awesome option inside of subj little brother UMIX that's called Average that's absolutely must have for unity mixer, that's why I love that family of mixers. And the idea of mutes is pretty nice, thanks. Could you add Average option to MUMIX too?

**Comment by mdemanett** [comment]
Yeah, should be easy, will do.

**Comment by vcvrackideas** [comment]
> Yeah, should be easy, will do.

Thanks! I also have an idea to invert a signal by right clicking on mute button (this option could be described in right click menu as you did in Switch matrices). Cheers!

**Comment by mdemanett** [comment]
I'd never thought of that, that MUMIX is really an 8x1 switch matrix -- but yeah will go ahead and bring over the inverting and otherwise standardize the features.

**Comment by mdemanett** [comment]
I think this is done; find a test build [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test1).

MUMIX got an average option.  However, adding inversion to it would have been weird, because I would have had to change how the switches work, which might break people's patches, like if they're parameter mapping the mute buttons.  

So instead, I made SWITCH81, which is basically MUMIX, but based on the SWITCH* style mixers.  The main difference is that on MUMIX, signal passes from a given input until you press a button to mute it, whereas on the others, the signal doesn't pass until a button is pressed to enable it.

It seemed weird to make a SWITCH81 without making a MATRIX81, so did that too.

Finally, added averaging to all SWITCH* and MATRIX*.
