### ISSUE TITLE
CMP strange behaviour?

### ISSUE THREAD

**Issue by giacecco** [bogaudio/BogaudioModules#155]
Hey Matt, All,
Unless I'm missing something, it looks to me like CMP's output gate goes up when the condition is verified, but does not go down when the condition _stops_ being verified. I must be misunderstanding something, but what is it? 

In the video below A is a static voltage that I manually change, and B a csaw oscillator. When A is >=B - and only when A is >=B - I should be hearing B. The left SCOPE shows the two signals, the right SCOPE shows the output of CMP's "A>=B". 

[![CMP issue?](http://img.youtube.com/vi/QTsNPEWxMfM/0.jpg)](http://www.youtube.com/watch?v=QTsNPEWxMfM "CMP issue?")

Thanks!

G.

**Comment by mdemanett** [comment]
I think you want to reduce the LAG knob -- zero it out, probably.  The lag setting puts a brake on the output changing when it otherwise would -- here I think the lag time is greater than the cycle time of the wave, so while the comparison is toggling internally in the module, the lag is causing the output to stick until the A input goes beyond the peak of the wave input, in each direction.  

With LAG set to zero, it should work like this:
![Screen Shot 2020-11-15 at 4 19 06 PM](https://user-images.githubusercontent.com/49971/99197112-6e8bd900-275e-11eb-9dc5-dd76be3d8980.png)

**Comment by giacecco** [comment]
Thanks a lot @mdemanett I've just double-checked following your advice and it was the lag parameter. Perhaps it was just me being confused, however I would suggest making CMP's default value for lag to be zero instead of the current 0.0something , unless of course there is a use case for this that I can't imagine, being a newbie. Thanks!
