### ISSUE TITLE
Request: longer sample history in RANALYZER

### ISSUE THREAD

**Issue by nickfeisst** [bogaudio/BogaudioModules#171]
Currently the Return Delay of RANALYZER allows for a 20 sample delay. Could this easily be increased?

Currently a module that I'm trying to debug has an internal sample delay of 32 samples, so it would be great to have it at least that, plus 2 for the cables.

**Comment by mdemanett** [comment]
Sure, I can do that in the next release.

If you want it now, and assuming you already or can build from source, just go into src/Ranalyzer.hpp and change maxResponseDelay to 34, or whatever.

**Comment by nickfeisst** [comment]
Great - thank you.

**Comment by diimdeep** [comment]
I tried to measure some very cool machine learning based device that requires 30ms delay.  
I would suggest to give user ability to set arbitrary 'return delay'. And also maybe there could be separate module that would allow to measure said delay in samples, for that signal maybe would have to start with some handshake sequence, IDK maybe that is too complicated.

**Comment by mdemanett** [comment]
I can add a mode where the delay is set in milliseconds, at least.

**Comment by mdemanett** [comment]
The current code ups the sample buffer max to 66 samples.  I'm not going to add a milliseconds mode -- it turns out to be a bit complicated.  Maybe down the road.

Meantimes though, here's a workaround to test something with a high latency.  This patch uses CHIRP (a VCO version of the test signal generator in RANALYZER) and a few delays to work things out such that the test signal, a trigger, and the device's response to the test signal all arrive at RANALYZER at the same time.  The device to test is being simulated by a delay and a VCF in the bottom row.

![Screen Shot 2021-04-14 at 7 44 10 PM](https://user-images.githubusercontent.com/49971/114794431-7a55e880-9d5a-11eb-98fe-929d6d7b446c.png)

[ranalyzer_high_device_latency.vcv.zip](https://github.com/bogaudio/BogaudioModules/files/6314326/ranalyzer_high_device_latency.vcv.zip)

Some notes on this:
  - Click TRIG on MANUAL to kick things off.
  - All the delays are set to 1 second; they all need to have the same TIME value; the OFFSET knob controls this (e.g. set it to 0.03 for 30ms).
  - All the delays are full wet.
  - TIME on CHIRP is set to about 1/3 of a second, which more or less matches the internal buffer size of RANALYZER.
  - The noise on the right side of the plot is some artifact coming from CHIRP, I need to look into that.
