### ISSUE TITLE
Limiter

### ISSUE THREAD

**Issue by blackearth2014** [bogaudio/BogaudioModules#22]
I don't know if its part of the design but the limiter modules seems to distort when the threshold is lowered to -6 and below during my test. My audio signal is reading -14db on the VU-BGA module. The Pressor module comp/limiter doesn't seem to have that issue on my system.

**Comment by mdemanett** [comment]
I wonder, if you switch the Pressor in your comparison to zero attack, zero sustain and peak detector, does it behave more or less like the limiter?  It ought to, since they're basically the same code, where limiter has those parameters fixed at those values.

Which means limiter is looking at the instantaneous voltage all the time -- at "-6db" it's going to clip any signal at about +/- 2.5V. 

Whereas Pressor isn't so sensitive, except at those settings.  VU's calculation likewise isn't so sensitive; it's using an RMS measure.  

Which is all just to say that both Pressor and VU will see a saw wave as quieter than a square wave, even if both are the same voltage peak-to-peak, while limiter will clip both.  

This is where I admit I don't actually know if this is how a limiter is supposed to work.  

(And I might need to look at VU, seems like it's reading low all the time.)

**Comment by blackearth2014** [comment]
A limiter is just a Compressor with high gain reductions that performs a brickwall. No signal goes about that set threshold like -0.5 : -1,,2,3. A compressor just ducks the sound based off a ratio like 1.5:1, 2:1, 3:1 and etc.

Your limiter should not be clipping or distorting when limiting at a certain threshold.

**Comment by mdemanett** [comment]
You have enlightened me.  I'll fix it.

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by mdemanett** [comment]
LMTR should be fixed.

**Comment by blackearth2014** [comment]
Cool Breeze
