### ISSUE TITLE
Stack is shifting 1V/oct 1 semitone lower.

### ISSUE THREAD

**Issue by AlbZamoraBell** [bogaudio/BogaudioModules#30]
I tried shifting the root of the patter from a sequencer using stack like you can see on the image. But notes above D#4 and below A3 are being shifted one semitone lower, meaning that if I want to send a CV to change from A3 to G3, I have to press F#3, instead of G3, and so on. Am I using STACK wrong or is it a bug?

![screen shot 2018-12-06 at 10 08 55 pm](https://user-images.githubusercontent.com/31251476/49627304-c41cb000-f9a3-11e8-9a4a-8d98676db9a1.png)

**Comment by mdemanett** [comment]
The issue here the CV input on stack expects a plain, linear bipolar (+/-5V) CV, which remote-controls what the knobs do at a (totally arbitrary) rate of 1 semitone per 1/10th volt.  But the Twelve-Key is outputting a 1V/octave pitch signal, which would give you 12 divisions per volt, and not linearly spaced in the volt.  So as in the picture, you're sending the 1V/octave signal to the thing that expects something else, and thus the odd results.

It might work better to switch the inputs -- send the root to the 1V/oct input on Stack, and then send the melody sequence output to the CV, setting the knobs there to get the pitches you want, as intervals from the root.
