### ISSUE TITLE
Feature request: multiplexer (mux) and demultiplexer (demux)

### ISSUE THREAD

**Issue by gilbertohasnofb** [bogaudio/BogaudioModules#41]
First of all, I absolutely love your modules, they are my favourite ones in VCV.

I would like to make a feature request: I think it would be really great to have a multiplexer (also known as mux) and a demultiplexer (demux) as part of your modules. A multiplexer takes N different inputs and routes just one of them to its single output according to a selector value. Basically:

![image](https://user-images.githubusercontent.com/5700795/55093454-501a2b00-50ac-11e9-8170-942dc71d9407.png)

A demultiplexer is the opposite, it takes a single input and routes it to a single one of its N outputs:

![image](https://user-images.githubusercontent.com/5700795/55093605-98d1e400-50ac-11e9-8915-c6cd0c6383c3.png)

One way of implementing the selector is to divide a range (say 10V) into 8 steps and use these as ranges for the selection. This is how it is implemented in a language such as Pure Data:

![image](https://user-images.githubusercontent.com/5700795/55093890-34fbeb00-50ad-11e9-8958-8a3a686ea5bc.png)

These can be very handy when creating complex patches that require the same signal to be sent to different modules at different times, as well as for selecting an input signal in a more complex way than a simple sequencer allows for.

**Comment by mdemanett** [comment]
Hey, glad you like the modules.

At first glance, I thought the Sequential Switch 1 & 2 in Fundamental do this -- but in fact they're clock triggered, not voltage addressed.  And four channels.  So, interesting idea, I'll think about it.

**Comment by gilbertohasnofb** [comment]
Thanks for considering it, I really appreciate it.

**Comment by MarcBoule** [comment]
Those three new modules seem to crash Rack at the moment (Win10). 
Disregard my comment if they are still in progress, but if not, I can add more details if needed.

**Comment by mdemanett** [comment]
Hey Marc, thanks for the heads up, pushed a fix.

**Comment by MarcBoule** [comment]
Hi Matt, thanks for the fix, all working now! 

I would like to make one small request regarding the three new modules. I have been meaning to make sequential switches also, in order to address an issue regarding missing first beats in sequencers and switches that happens some times. But your modules are so nice and I abhor redundant modules, so I'm taking a shot here. As you may know, Andrew currently has a standard up (but hasn't implemented it in SEQ3 and PM8/16 yet), but I do this in all my sequencers and it is a great help in this area. So I'm taking a shot here to see if you would be interested in applying this standard also:

> Therefore, modules with a CLOCK and RESET input, or similar variants, should ignore CLOCK triggers up to 1ms after receiving a RESET trigger.

https://vcvrack.com/manual/VoltageStandards.html#timing

If you know all about this, please forgive my verbosity, just want to make it as clear as possible :-) 

In short, when the clock signal has a few Rack samples of delay (going through clock divider, logic, switch or whatever), it can reach the sequential element a few samples after the reset, and this makes it such that when we reset a clock that was low, the new clock edge will then immediately trigger the sequential element to switch right after the reset, and the first step lasted only 1 rack sample or so, which is obviously much too short. 

Here is also my very short description to Andrew which helped convince him of the need for such a standard. 

https://github.com/VCVRack/Rack/issues/938#issuecomment-407235993

The example above was a minimal working example for more broader cases.

So when I build the following test patch with a bunch of sequential elements, the only ones to play correctly out of reset are PhraseSeq16 and VCV-Router4:1. 

![image](https://user-images.githubusercontent.com/33604154/55677018-8dea3100-58ae-11e9-9ce1-4672b8152e32.png)

If you want to try the patch yourself, here it is.

[SeqTest1.zip](https://github.com/bogaudio/BogaudioModules/files/3051093/SeqTest1.zip)

If you don't want to get into this kind of stuff, no problem, but since I like your collection so much, I could't not make the suggestion. Thanks for your modules!

**Comment by mdemanett** [comment]
Hey Marc, this makes total sense, I'll do it.

And thank you for your modules!  They're awesome.

**Comment by gilbertohasnofb** [comment]
@mdemanett Thanks for implementing this! Do you plan to make a new release soon in order to include the new modules for people not using git?

**Comment by mdemanett** [comment]
@gilbertohasnofb should be any day now, it's queued to build in the community system, the timing is out of my hands.

**Comment by gilbertohasnofb** [comment]
@mdemanett The new release is now available in VCV. The new modules work like a charm, thank you so much for implementing them -- they will be super handy! I am closing this issue now.

**Comment by mdemanett** [comment]
Reopening until next the release, which will have the CLOCK/TRIGGER fix as above...coming soon, finally.

**Comment by MarcBoule** [comment]
Thanks Matt!
