### ISSUE TITLE
Feature Request: Gate-to-Trigger Utility

### ISSUE THREAD

**Issue by mjarmy** [bogaudio/BogaudioModules#90]
Bogaudio has DGATE, a trigger-to-gate utility, but does not seem to have a gate-to-trigger utility, unless I am overlooking it.  Is there a way to do this with the existing Bogaudio tools?

If not, it would be cool to have a polyphonic utility with a gate input, and trigger outputs for rise and fall.

**Comment by mdemanett** [comment]
There's no specific module for that...I've thought about it, but haven't gotten around to it because it's fairly easy to fake: with any ADSR envelope, set attack, sustain and release to zero and decay to very short.  DADSRH has an end-of-cycle output, which if release is zero, will give you a trigger when the gate falls.  "AD" would almost do it all in 3HP, but it retriggers while the gate is high.

**Comment by mjarmy** [comment]
Got it, thanks.
